In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('churning.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [5]:
#divide the data into two features ,one is independent features and other one is the dependent feature.
x=df.iloc[:,3:13]
y=df.iloc[:,-1]

In [6]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [7]:
#in the independent features again there is categorical features.So,performing feature engineering.
geography=pd.get_dummies(df['Geography'],drop_first=True)
gender=pd.get_dummies(df['Gender'],drop_first=True)

In [8]:
#now we concate each other.
x=pd.concat([x,geography,gender],axis=1)

In [9]:
x.drop(['Geography','Gender'],axis=1,inplace=True)

In [10]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Germany  Spain  Male  
0               1        101348.88        0      0     0  
1               1        112542.58        0      1     0  
2               0        113931.57        0      0     0  
3               0         93826.63        0      0     0  
4               1         79084.10        0      1     0

In [11]:
#now split the data into training set and testing set 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [12]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(7500, 11) (2500, 11) (7500,) (2500,)


In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [14]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [15]:
x_train

array([[-0.73550706,  0.01526571,  0.00886037, ...,  1.76021608,
        -0.57468161, -1.08726059],
       [ 1.02442719, -0.65260917,  0.00886037, ..., -0.56811207,
        -0.57468161, -1.08726059],
       [ 0.80829492, -0.46178778,  1.39329338, ..., -0.56811207,
         1.74009395, -1.08726059],
       ...,
       [ 0.90092304, -0.36637708,  0.00886037, ..., -0.56811207,
        -0.57468161,  0.91974271],
       [-0.62229491, -0.08014499,  1.39329338, ..., -0.56811207,
         1.74009395, -1.08726059],
       [-0.28265848,  0.87396199, -1.37557264, ...,  1.76021608,
        -0.57468161, -1.08726059]])

In [16]:
x_test

array([[-0.55025082, -0.36637708,  1.04718513, ...,  1.76021608,
        -0.57468161, -1.08726059],
       [-1.31185979,  0.11067641, -1.02946438, ..., -0.56811207,
        -0.57468161, -1.08726059],
       [ 0.57157862,  0.3014978 ,  1.04718513, ..., -0.56811207,
         1.74009395, -1.08726059],
       ...,
       [ 1.95070838,  0.01526571, -1.37557264, ..., -0.56811207,
        -0.57468161, -1.08726059],
       [ 0.29369426, -0.08014499,  0.70107688, ...,  1.76021608,
        -0.57468161,  0.91974271],
       [ 0.870047  , -0.74801987, -0.68335613, ..., -0.56811207,
        -0.57468161,  0.91974271]])

In [20]:
# next to create a ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import ReLU,LeakyReLU,PReLU,ELU
from tensorflow.keras.layers import Dropout

In [22]:
#now first intialize the ANN
classifier=Sequential()

In [23]:
#first import the input layer
classifier.add(Dense(units=11,activation='relu'))

In [24]:
# next import the first hidden layer
classifier.add(Dense(units=6,activation='relu'))

In [25]:
# we import the another hidden layer
classifier.add(Dense(units=6,activation='relu'))

In [26]:
# we create a output layer
classifier.add(Dense(units=1,activation='sigmoid'))

In [29]:
#after that we compile a ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [52]:
model_history=classifier.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=30)

Epoch 1/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3135 - accuracy: 0.8682 - val_loss: 0.3504 - val_accuracy: 0.8566
Epoch 2/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3135 - accuracy: 0.8704 - val_loss: 0.3542 - val_accuracy: 0.8526
Epoch 3/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3131 - accuracy: 0.8684 - val_loss: 0.3519 - val_accuracy: 0.8550
Epoch 4/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3134 - accuracy: 0.8670 - val_loss: 0.3516 - val_accuracy: 0.8546
Epoch 5/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3127 - accuracy: 0.8676 - val_loss: 0.3556 - val_accuracy: 0.8582
Epoch 6/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3127 - accuracy: 0.8664 - val_loss: 0.3496 - val_accuracy: 0.8558
Epoch 7/30
503/503 [==============================] - 1s 1ms/step - loss: 0.3121 - accuracy: 0.8702 - val_loss: 0.3518 - val_accuracy: 0.8570
Epoch 

In [53]:
x_train.shape

(7500, 11)

In [54]:
#make the predections also.
y_pred=classifier.predict(x_test)
y_pred=(y_test>=0.5)

79/79 [==============================] - 0s 523us/step


In [55]:
#make the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2116,    0],
       [   0,  384]], dtype=int64)

In [56]:
#make classification report on this.
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00      2116
        True       1.00      1.00      1.00       384

    accuracy                           1.00      2500
   macro avg       1.00      1.00      1.00      2500
weighted avg       1.00      1.00      1.00      2500



In [58]:
#get weights
classifier.get_weights()

[array([[-0.06040627,  0.06037453,  0.16024719,  0.11090348,  0.2614032 ,
         -0.06135819,  0.05054236,  0.07547148,  0.10372623,  0.08262281,
          0.04964312],
        [-0.22772242, -0.9096578 ,  0.3096231 , -0.07810889, -0.18536052,
          0.22582376,  0.78840494, -0.24201448, -0.45873055, -1.2194178 ,
          0.08190832],
        [ 0.03018771,  0.08337368,  0.08278858,  0.62834466,  0.7821393 ,
         -0.11514267,  0.2590384 ,  0.2357948 , -0.04314716,  0.34386846,
          0.30060464],
        [-1.2992831 ,  0.03994787,  0.35725558, -0.27365115, -0.6821358 ,
          0.4715544 , -0.49423712, -0.60932595, -1.056292  ,  0.22769573,
          0.19054383],
        [ 0.0525628 , -0.02296066, -0.33176813,  0.05750361,  0.6131699 ,
         -0.35741824, -0.09605616, -1.0499876 ,  0.27072984,  0.12506601,
          1.1947291 ],
        [ 0.24373661,  0.04237556,  0.62426794, -0.31357938, -0.28518826,
          0.20312534, -0.01210181, -0.23054416,  0.08353184, -0.4308249